### ISSUE TITLE
Vagrant VISTA on Cache

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nodeVISTA#71]
We want a clean Vagrant Cache VISTA. Right now we have [1] VISTA on GT.M from OSEHRA and [2] AINA VISTA which is Cache in Vagrant but seems to be missing pieces - Cache's Windows apps can't connect. 

__Goal:__ let's get "OSEHRA VISTA" on Cache in a Vagrant using a revision of OSEHRA's Vagrant and its scripts. The pieces seem to be there.

__Related__: [node on Cache too](https://github.com/vistadataproject/nodeVISTA/issues/18)

## Cache install by Vagrant as opposed to GT.M Install

Look inside osehraVISTA/vagrantVISTA/Scripts/Install/Cache or in your nodeVISTA VM, /vagrant/cache ... install.sh has ...

```text
# unzip the cachekit in a temp directory
cachekit=/root/cache-2011.1.2.701-lnxrh5x64.tar.gz

tempdir=/tmp/cachekit2011.1.2.701

mkdir $tempdir

chmod og+rx $tempdir

cd $tempdir

tar xzf $cachekit
```

The GT.M equivalent, gtm/install.sh has 

```text
curl -s --remote-name -L http://downloads.sourceforge.net/project/fis-gtm/GT.M%20Installer/v0.12/gtminstall
```

but that's because you can download GT.M without accepting licenses etc. You have to manually fetch Cache from __https://download.intersystems.com/download/register.csp__

## in ubuntu/auto-installer.sh

there's

```
# Install GTM

cd GTM

./install.sh -v V6.2-000
```

which would need to be replaced by?

```text
cd Cache

./install.sh
```

## Problem?

GTM has a follow on script "createVISTAInstance" which /Cache lacks or does the main cache install do this work too?

Ed said

> To load VistA, you'd need to either upload a bunch of routines and global variables that contain the relevant information, or copy a database. From the script, I got the impression that copying the database is part of the kit and its install script.

## Cache Key - unlike GT.M, it needs one

See S. Bruno Esq. 

## Once it works - using Cache clients from Windows

Ed ...

> Cache has a number of tools to manage their systems. One of them is the Studio. In order to use it, you need to have Cache installed on a Windows machine (no need to buy a license for that type of installation, their free developer version will work just fine, it just limits the number of things you can do simultaneously).
>
> The other tool is the Cache Management Portal, again, you run it from a Windows machine in the same fashion as Studio.
>
> Both tools connect to their target systems using a TCP/IP connection (albeit on different ports). Using Studio, you can view and modify code. Using the Management Portal, you can manage all settings in the Cache system.

but neither work with AINA. It must be missing some Cache components. Hopefully a clean install won't be missing those components.

```text
---------------------------
Studio
---------------------------
Unable to obtain server's version 
ERROR #5002: Cache error: <NOLINE>getMetaInfoRecursive+9^%occMetaInfoCpp
---------------------------

And when I try to connect to the Cache Management Portal, the error message is:
Error: <CLASS DOES NOT EXIST>%OnAfterCreatePage+2^%ZEN.Portal.standardPage.1 *%SYS.EMS
```

![screencache](https://cloud.githubusercontent.com/assets/1831390/19208678/3f5d80de-8cb2-11e6-966c-1bf5305f69c7.png)

**Comment by conorcaregraf** [comment]
Other BG: doing manual install first following OSEHRA [install FOIA VISTA](https://www.osehra.org/content/foia-vista)

And Note /cache directory in Vagrant VISTA lacks installVISTA etc. but it does have restore and other scripts that deal with CACHE.dat. Ex ...

```text
cp /opt/cachesys/VISTA/CACHE.DAT /opt/backup/CACHE-`date +%m%d%Y`.DAT
```

**Comment by mfuroyama** [comment]
Current WIP feature branch: [universal-fidelity-vm](https://github.com/vistadataproject/nodeVISTA/tree/universal-fidelity-vm/universalFidelityVM)

The universal fidelity VM setup scripts are based on and utilize the OSEHRA VistA scripts.

### Current Iteration
* Introduce a single entry point script: 'createUniversalVM.sh' to bootstrap the installation/provision process
* Stand up a CentOS 6.5 VM (as opposed to an Ubuntu 14 VM used in the OSEHRA VistA scripts) to support Cache installation
* Create a custom provisioning script, 'provisionVM.sh' to serve as an option router for service installation
* Tweak the OSEHRA VistA 'autoInstaller.sh' for RHEL to support our custom database installation
* Create GT.M and Cache base installation scripts
* Create project specific setup scripts for GT.M installation:
   * Remove EWD installation
   * Add separate nvm/Node.js/npm installation
   * Add GT.M setup previously done in EWD installation

Currently, GT.M/VistA installation for VDP and LDSR have been tested and works like the original OSEHRA VistA setup. Automated Cache installation works, but VistA CACHE.DAT installation has not been scripted and/or automated yet.

# Todo list
* Manually install VistA on Cache instance
* Figure out how to automate a VistA installation on Cache 
* Create script to install VistA on Cache, integrate script with provisioner
* Create project specific setup scripts for Cache installation 
* Install FMQL on Cache instance using CSP
* Clean up messaging, error handling

**Comment by mfuroyama** [comment]
_Current WIP feature branch: [cache-vista-vm](https://github.com/vistadataproject/nodeVISTA/tree/cache-vista-vm)_

## Background
Initially, the hope was to use the OSEHRA VistA scripts to stand up and configure a Cache-based VistA instance in a Vagrant-based VM. Unfortunately the Cache scripts in the OSEHRA VistA set were basically just placeholders, so I was out of luck..I had to come up with my own set of scripts through trial-and-error.


## Approach
The approach to creating Cache-based VistA instance was loosely based on the existing OSEHRA VistA scripts:

* Acquire an evaluation copy of the Cache x86_64 Linux installer package
* Use Vagrant to stand up and configure a CentOS 6.5 Linux box (based on Cache Linux installation requirements)
* Manually install and configure Cache the first time in the CentOS box, preserving the _cache.cpf_ config file after setup
* Start all over and automate the Cache installation by importing the generated _cache.cpf_ file to the Cache installation
* Retrieve and import an OSEHRA VistA FOIA _CACHE.DAT_ image from the [OSEHRA VistA FOIA archive website](http://foia-vista.osehra.org/DBA_VistA_FOIA_System_Files/)
* Create and configure development user account (**vistad**)
* Clean up


## Results
Surprisingly to me, the approach described above to install and configure Cache seemed to work: I was able to access the Cache installation using the web-based Management Portal and see that the VistA database was, in fact, installed via the _CACHE.DAT_ file. I was also able to use the Cache terminal to browse the VistA file structure via Fileman. Unfortunately, there were also a handful of issues regarding the instance.


## Issues
As far as I can tell, the VistA FOIA instance stored in the imported _CACHE.DAT_ file seemed pretty bare-bones: There were no patients, and hardly any data. More importantly, the RPC broker service wasn't configured properly in the Vista FOIA instance. I tried to initialize the VistA instance after installation using the procedure described in the [OSEHRA VistA Documentation (https://github.com/OSEHRA/VistA/blob/master/Documentation/Initialization.rst) with no luck.


## Mitigations
What I ended up doing was importing the _CACHE.DAT_ file from the JLV **VISTA AINA** VM snapshot and importing that into the new Cache installation, instead of the VistA FOIA _CACHE.DAT_. The **VISTA AINA** _CACHE.DAT_ seems to be more thoroughly configured, especially the RPC broker.  By replacing the _CACHE.DAT_ file, and after manually starting the RPC Broker process (8994.1) I was able to access the new instance via CPRS (1.0.30.69).  The Management Portal was also still accessible. This approach might be a great compromise, since ultimately, we were going with a fresh install because the Cache utilities wouldn't work with the **VISTA AINA** snapshot VM.

Unfortunately, there are issues: the Python _brokerRPC.py_ utility failed with a socket connection error, and the Windows Cache Cube-based **Studio** gave me connection errors, but using the **VISTA AINA** _CACHE.DAT_ file has gotten me the farthest along that I've been in a week.

Eventually, if we settle on this approach, we'll need to figure out how to manage and retrieve the extracted **VISTA AINA** _CACHE.DAT_ file, and how to start the RPC broker service automatically.


## Procedures
For now, the current set of scripts works as follows:
* Download an evaluation copy of the RHEL x86\_64 Cache installer package, and place the _.tar.gz_ file in the _resources_ directory
* Retrieve the _CACHE.DAT_ file from **VISTA AINA** and place the file in the _resources_ directory
* Run the _./createVM.sh_ command from the terminal (this will start the Vagrant stand-up and provisioning process)
* When done, manually start the RPC broker process:
    * SSH into the VM by entering `vagrant ssh` in the terminal
    * In the VM, enter `csession prod -U VISTA` to enter the Cache installation
    * At the `VISTA> ` prompt, enter `D STRT^XWBTCP(9430)` to start the RPC broker
    * At the `VISTA> ` prompt, enter `H` to exit Cache

That's it.


## Todo List

* Set up automatic start of the RPC broker service [RPC Broker 1.1 System Management Guide](http://www.va.gov/vdl/documents/Infrastructure/Remote_Proc_Call_Broker_(RPC)/xwb_1_1_sm.pdf)
* Come up with a scheme to manage and retrieve the extracted **VISTA AINA** _CACHE.DAT_ file.
* Create a solid README.md file/documentation

**Comment by mfuroyama** [comment]
More observations/notes as I continue to struggle with the VistA Cache installation:

**A VistA Cache instance VM will most likelly not work with a Cache single-user evaluation copy**
From configuring to running, users are limited in what they can do due to the single-user license limitations imposed by Cache.  For example, I tried installing FMQL, and although the install instructions were okay and I got FMQL installed, the CSP endpoint wasn't working. I can't say with 100% confidence, but I'm pretty sure that almost all of the issues we're experiencing, including the FMQL install, would be mitigated with a multi-user Cache install. Basically, running VistA on a single-user evaluation copy of Cache makes things functionally unstable and not worth using. To continue, I'll probably need to get my hands on a multi-user installation package for Cache. The plan is to ask Melcolm or Brad of HRG if they have such an installer package...

**OSEHRA VistA post-install Python scripts work with Cache...sort of**
The OSEHRA VistA package comes with post-install Python scripts which configure a clean install of VistA and set the database with sample data for testing. The scripts configure things in VistA like Taskman, and RPC broker listener service, and sets up clinics, providers and patients.

At first, I thought these scripts only worked with a GT.M installation, but it turns out, with a little bit of tweaking, I can get the scripts to run with Cache as well...sort of.  Unfortunately, while running the scripts, I also run into user/license issues. However, once we get a multi-user Cache install, with these scripts, not only can we create clean installs of Cache Vista on our VM, but in the future, we also gain the ability to add custom data to the database.  I've committed and pushed these scripts in the [cache-vista-vm](https://github.com/vistadataproject/nodeVISTA/tree/cache-vista-vm) WIP feature branch.

## Action Items

* Get a multi-user install package for Cache (RHEL edition)
* Run the Python post-install scripts to completion, test services are working (Taskman, etc.)
* Re-run FMQL CSP install and test - related to CHCS CSP install task
* Clean up scripts, add moar documentation

**Comment by mfuroyama** [comment]
First working iteration of the scripts complete: ['cache-vista-vm' pull request here](https://github.com/vistadataproject/nodeVISTA/pull/73)
